### ISSUE TITLE
Icon size and background color  in Overview

### ISSUE THREAD

**Issue by fastrizwaan** [sustmi/gnome-shell-extensions-sustmi#33]
Hi, could we have 48px size icons in overview, also the 'black background' doesn't look beautiful. please see:
https://www.youtube.com/watch?v=KMXK_ZzT9-8

![81138_990x557](https://cloud.githubusercontent.com/assets/1161682/9697808/71b8343e-53ba-11e5-80e6-1255c69ade7c.jpg)

Please consider allowing different sizes and transparency to the icon background. thanks.

**Comment by fastrizwaan** [comment]
Hi, Only transparency would do. Currently only solid colors are allowed as icon background.

Please add "no" background or transparency to windows overlay icons. Thanks.

**Comment by sustmi** [comment]
Hi @fastrizwaan, you should be able to click on the color button ("Background color") and add custom color (by clicking the "plus" button) with full transparency (bottom slider).
![Custom color](https://cloud.githubusercontent.com/assets/885946/9980777/a1175ea2-5fa5-11e5-8302-b1d53aca2d99.png)

**Comment by fastrizwaan** [comment]
Thank you, could you please consider adding 
[ x ] Transparent 
beside colors so that it would be easier.

**Comment by sustmi** [comment]
Hi @fastrizwaan. I am sorry but the *Transparent* checkbox will be too much work for me with very little outcome. Also, it would add strange behavior when you set the color to transparent in color picker dialog but unchech the *Transparent* checkbox. What should be the result then - transparent or non-transparent?

Please check the new design that was added in https://github.com/sustmi/gnome-shell-extensions-sustmi/issues/45.

I am closing this issue but I am open to any follow-up discussion.
Also, I am sorry for not replying for so long.

*Note that https://github.com/sustmi/gnome-shell-extensions-sustmi repository is deprecated because I split the repository into two separate repositories so please post any new issues or pull requests to https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons.*
