### ISSUE TITLE
Shell gets stuck in overview if screen is locked in overview and then VT is changed

### ISSUE THREAD

**Issue by smithfred** [sustmi/gnome-shell-extensions-sustmi#44]
To reproduce:
* open at least one window
* open the overview
* lock the session
* switch to another VT (e.g. Ctrl-Alt-F(n), or switching to another user)
* switch back to first session and unlock.

The shell is now stuck in the overview, and it's not possible to return to the normal view via keyboard, mouse etc.

The overlay icons also disappear, as do the window close buttons/borders shown when hovering.

This doesn't happen without the extension enabled.

This means for example that if the user switches to a different session when in the overview, and then switches back, their first session is now broken.

**Comment by sustmi** [comment]
Hello @smithfred, sorry I did not have time to look at this issue sooner.

So far I was able to discover this:
1. Gnome Shell gets stuck only when I am using Wayland. If I select legacy Xorg the icons disappear but by pressing escape key I can hide window overlay and everything works well.
2. The problem may be in Gnome Shell life-cycle management of `WindowOverlay` object. When I log calls of `WindowOverlay` methods I can see that Gnome Shell calls `_onDestroy()` and then `hide()` which causes the following error:
```
gnome-shell[1712]: JS WARNING: [/home/mirek/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js 99]: reference to undefined property this._windowOverlayIconsExtension
gnome-shell[1712]: JS ERROR: TypeError: this._windowOverlayIconsExtension is undefined
	enable/wsWinOverInjections.hide<@/home/mirek/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:99:9
	injectToFunction/objectPrototype[functionName]@/home/mirek/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:237:35
	Workspace<._zoomWindowFromOverview@resource:///org/gnome/shell/ui/workspace.js:1753:13
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	Workspace<.zoomFromOverview@resource:///org/gnome/shell/ui/workspace.js:1745:12
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	WorkspacesView<.animateFromOverview@resource:///org/gnome/shell/ui/workspacesView.js:161:17
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	WorkspacesDisplay<.animateFromOverview@resource:///org/gnome/shell/ui/workspacesView.js:522:13
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	ViewSelector<.animateFromOverview@resource:///org/gnome/shell/ui/viewSelector.js:297:9
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	Overview<._animateNotVisible@resource:///org/gnome/shell/ui/overview.js:613:9
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	Overview<.hide@resource:///org/gnome/shell/ui/overview.js:601:9
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
	ViewSelector<._onStageKeyPress@resource:///org/gnome/shell/ui/viewSelector.js:429:17
	wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
```
because it tries to call `this._windowOverlayIconsExtension.box.hide();` but `this._windowOverlayIconsExtension` is null (probably because the object is getting destroyed.

I will try to find some fix or workaround for this.

**Comment by smithfred** [comment]
Thanks for the reply and investigaion so far, much appreciated :)

**Comment by sustmi** [comment]
Hi @smithfred . The issue was fixed in https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/commit/67bdded32ecf1619d052cecb00598efe0817e557 and the fix is released in v29 of the extension which will be available soon after reviewing on https://extensions.gnome.org/extension/302/windowoverlay-icons/.
