### ISSUE TITLE
Better default settings values for nicer design

### ISSUE THREAD

**Issue by jancborchardt** [sustmi/gnome-shell-extensions-sustmi#45]
Currently the default view looks like this, small icons on the bottom right with a dark background:
![windowoverlay icons current](https://user-images.githubusercontent.com/925062/28873577-937958ba-778e-11e7-9798-c33465feb1d9.png)

Here is how a different default could look, which makes the apps more quick to distinguish based on their prominent icons:
![windowoverlay icons modified](https://user-images.githubusercontent.com/925062/28873575-9378636a-778e-11e7-90a1-8e2f3a4d7f43.png)

- larger icons (128px)
- positioned in the center
- transparent background
- opacity increased on hover instead of decreased to emphasize the app
![windowoverlay icons changes](https://user-images.githubusercontent.com/925062/28873576-9378de1c-778e-11e7-82d2-00d0257b4bd0.png)

I’m also wondering what the general plan for GNOME design is – stay without icons or are you thinking about adding them to the windows @allanday @jimmac?

**Comment by sustmi** [comment]
Thanks for the suggestion @jancborchardt.
I had to give it few days to get used to it but now I think that it looks much better.

The changes are done in https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/commit/7b3625d877e9c80251bed0fb7aa5b66665e57789 and will be present in the next release.

*Note that https://github.com/sustmi/gnome-shell-extensions-sustmi repository is deprecated because I split the repository into two separate repositories so please post any new issues or pull requests to https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons.*

**Comment by sustmi** [comment]
Btw, @jancborchardt, would you mind if I used your second screenshot from this issue in `README.md` of the extension?

**Comment by jancborchardt** [comment]
@sustmi awesome, thank you so much! :)

And yes, please go ahead and use the screenshot for the readme. :) Happy to help.
