### ISSUE TITLE
Icon overlaps with window title in Shell 3.26

### ISSUE THREAD

**Issue by dsboger-zz** [sustmi/gnome-shell-extensions-sustmi#49]
GNOME Shell 3.26 moved the window title to a "floating" label and now, when the overlay icon is in the center bottom of the window thumbnail it overlaps with the title label.

![image](https://user-images.githubusercontent.com/2356842/31832796-afb65962-b59e-11e7-8ec3-6303d84bb863.png)

**Comment by sustmi** [comment]
Hi @dsboger. What do you think that would be a good solution for this?

I could increase the spacing (https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/blob/4c884dcbb03134bd1957ddf7f363eae64904b94a/extension.js#L200) between the icon and border of the window in the `VerticalAlignment.BOTTOM` mode so that the icon does not overlap with the label.

Note that the overlapping would still happen in `VerticalAlignment.MIDDLE` mode when the icon would be bigger than the window.

**Comment by dsboger-zz** [comment]
I think that increasing the bottom margin will do. The situation you mention of having the icon bigger than the window thumbnail would be a corner case. I think the overlay icon should shrink to fit inside the window thumbnail if necessary.

Thank for your efforts!

**Comment by dsboger-zz** [comment]
I've liked your solution! Closing this.
